#!/bin/bash

echo "🐳 Kafka Configuration Information"
echo "=================================="
echo ""

echo "📋 Current Setup:"
echo "   - Kafka Version: Confluent Platform 7.4.0 (Kafka 3.4.x)"
echo "   - Mode: KRaft (No Zookeeper required)"
echo "   - Port: 9092"
echo "   - Self-managed metadata"
echo ""

echo "🔄 Kafka Modes:"
echo "   Traditional Mode (Kafka < 2.8):"
echo "     ├── Requires Zookeeper"
echo "     ├── Zookeeper manages metadata"
echo "     └── More complex deployment"
echo ""
echo "   KRaft Mode (Kafka 2.8+):"
echo "     ├── No Zookeeper dependency"
echo "     ├── Self-managed metadata"
echo "     └── Simplified deployment"
echo ""

echo "🚀 Benefits of KRaft Mode:"
echo "   ✅ Reduced complexity (no Zookeeper)"
echo "   ✅ Better performance"
echo "   ✅ Improved scalability"
echo "   ✅ Enhanced security"
echo "   ✅ Production-ready since Kafka 3.0"
echo ""

echo "🔧 Configuration:"
echo "   - KAFKA_PROCESS_ROLES: broker,controller"
echo "   - KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093"
echo "   - KAFKA_LOG_DIRS: /tmp/kraft-combined-logs"
echo ""

echo "📊 Monitoring:"
echo "   - Check Kafka status: docker-compose ps kafka"
echo "   - View logs: docker-compose logs kafka"
echo "   - Test connection: telnet localhost 9092"
echo ""

echo "⚠️  Migration Notes:"
echo "   - If migrating from Zookeeper mode, data migration required"
echo "   - KRaft mode is backward compatible for clients"
echo "   - Recommended for new deployments" 